#
# Copyright (C) 2017-2019 Dremio Corporation. This file is confidential and private property.
#

{{- if $.Values.DremioAdmin }}
# dremio-admin pod is used to run offline commands like
# clean, restore or set-password against the Dremio cluster.
# The Dremio cluster should be shutdown before attempting to
# create the dremio-admin pod.
# You connect to the pod (kubectl exec -it dremio-admin -- bash),
# go to /opt/dremio/bin and run dremio-admin commands as documented.
apiVersion: v1
kind: Pod
metadata:
  name: dremio-admin
  {{- include "dremio.admin.podAnnotations" $ | nindent 2}}
  {{- include "dremio.admin.podLabels" $ | nindent 2}}
spec:
  {{- include "dremio.admin.serviceAccount" $ | nindent 2 }}
  {{- include "dremio.podSecurityContext" $ | nindent 2 }}
  containers:
  - name: dremio-admin
    {{- include "dremio.containerSecurityContext" $ | nindent 4 }}
    image: {{ $.Values.dremio.image.repository }}:{{ $.Values.dremio.image.tag }}
    imagePullPolicy: {{ .Values.dremio.image.pullPolicy }}
    stdin: true
    tty: true
    resources:
      {{- .Values.coordinator.resources | toYaml | nindent 6 }}
    volumeMounts:
    - name: dremio-master-volume
      mountPath: /opt/dremio/data
    - name: dremio-config
      mountPath: /opt/dremio/conf
    - name: dremio-license
      mountPath: /opt/dremio/license
    {{- include "dremio.coordinator.extraVolumeMounts" $ | nindent 4 }}
    env:
      - name: DREMIO_HELM_VERSION
        value: "{{ .Chart.Version }}"
      - name: DREMIO_JAVA_SERVER_EXTRA_OPTS
        value: >-
          {{- include "dremio.coordinator.extraStartParams" $ | nindent 10 }}
          -XX:ActiveProcessorCount={{- include "dremio.coordinator.activeProcessorCount" $ }}
    command: ["sleep", "infinity"]
  {{- include "dremio.admin.extraInitContainers" $ | nindent 2 }}
  {{- include "dremio.admin.priorityClassName" $ | nindent 2 }}
  {{- include "dremio.admin.nodeSelector" $ | nindent 2 }}
  {{- include "dremio.admin.tolerations" $ | nindent 2 }}
  volumes:
  - name: dremio-master-volume
    persistentVolumeClaim:
      claimName: dremio-master-volume-dremio-master-0
  - name: dremio-config
    configMap:
      name: dremio-config
  - name: dremio-license
    secret:
      secretName: dremio-license
      items:
        - key: license
          path: key
  {{- include "dremio.coordinator.extraVolumes" $ | nindent 2 }}
{{- end -}}
