apiVersion: v2
dependencies:
- alias: mongodbOperator
  name: dremio-mongodb-operator-helm
  repository: oci://quay.io/dremio
  version: 1.21.1-dremio-20251103174242-5f562d3
- condition: nats.enabled
  name: nats
  repository: https://nats-io.github.io/k8s/helm/charts/
  version: 1.3.1
- alias: opensearchOperator
  condition: opensearch.enabled
  name: dremio-opensearch-operator-helm
  repository: oci://quay.io/dremio
  version: 2.8.0-dremio-20251025004440-1f5a2bd
home: https://www.dremio.com/
keywords:
- dremio
- data
name: dremio-helm
type: application
version: 3.2.1
